# This version has the relay ENABLED
substitutions:
  restore_mode_relay: RESTORE_DEFAULT_ON
  reset_button: GPIO0

esphome:
  name: "plug-s31"
  friendly_name: "Plug-S31"
  #device_description: "Sonoff S31 Power Monitor"
  #hardware_info: "ESP8266"
  project:
    name: "SB-Inovations.Sonoff_S31"
    version: "0.0.1"
  name_add_mac_suffix: True


dashboard_import:
  package_import_url: github://bnevets27/ESPHome-Projects/config/sonoff-s31.yaml@main
  import_full_config: true

#packages:
#  device: !include common/devices/plugs/sonoff-s31.yaml
#  base: !include common/base-8266.yaml

packages:
  remote_package:
    url: https://github.com/bnevets27/ESPHome-Projects/
    ref: main
    files:
      - common/base-generic.yaml
      - common/base-diagnostic-8266.yaml
      - common/base-network.yaml
      - common/devices/plugs/sonoff-s31.yaml
    refresh: 0d
